/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardWorkspaceIdRouteImport } from './routes/onboard.$workspaceId'
import { Route as DashboardDomainRouteImport } from './routes/dashboard.$domain'
import { Route as BDomainRouteImport } from './routes/b.$domain'
import { Route as ApiWorkspaceStateRouteImport } from './routes/api/workspace-state'
import { Route as ApiVoteRouteImport } from './routes/api/vote'
import { Route as ApiVerifyDomainRouteImport } from './routes/api/verify-domain'
import { Route as ApiTicketRouteImport } from './routes/api/ticket'
import { Route as ApiScreenshotUploadRouteImport } from './routes/api/screenshot-upload'
import { Route as ApiCommentRouteImport } from './routes/api/comment'
import { Route as ApiAuthStateRouteImport } from './routes/api/auth-state'
import { Route as DashboardDomainIndexRouteImport } from './routes/dashboard.$domain.index'
import { Route as DashboardBillingSuccessRouteImport } from './routes/dashboard.billing.success'
import { Route as DashboardDomainSettingsRouteImport } from './routes/dashboard.$domain.settings'
import { Route as DashboardDomainIntegrationsRouteImport } from './routes/dashboard.$domain.integrations'
import { Route as DashboardDomainDeliveriesRouteImport } from './routes/dashboard.$domain.deliveries'
import { Route as DashboardDomainClaimRouteImport } from './routes/dashboard.$domain.claim'
import { Route as DashboardDomainBillingRouteImport } from './routes/dashboard.$domain.billing'
import { Route as ApiSignupStartCheckoutRouteImport } from './routes/api/signup/start-checkout'
import { Route as ApiSignupAbandonRouteImport } from './routes/api/signup/abandon'
import { Route as ApiScreenshotKeyRouteImport } from './routes/api/screenshot.$key'
import { Route as ApiPublicTicketsRouteImport } from './routes/api/public.tickets'
import { Route as ApiOnboardRenameRouteImport } from './routes/api/onboard/rename'
import { Route as ApiMeWorkspacesRouteImport } from './routes/api/me.workspaces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminTicketsRouteImport } from './routes/api/admin/tickets'
import { Route as ApiAdminRedriveRouteImport } from './routes/api/admin/redrive'
import { Route as ApiAdminIntegrationsRouteImport } from './routes/api/admin/integrations'
import { Route as ApiAdminDeliveriesRouteImport } from './routes/api/admin/deliveries'
import { Route as ApiAdminBillingSummaryRouteImport } from './routes/api/admin/billing-summary'
import { Route as DashboardDomainTicketsIdRouteImport } from './routes/dashboard.$domain.tickets.$id'
import { Route as ApiIntegrationsSlackInstallRouteImport } from './routes/api/integrations/slack.install'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack.callback'
import { Route as ApiAdminTicketsIdRouteImport } from './routes/api/admin/tickets.$id'
import { Route as ApiAdminIntegrationsIdRouteImport } from './routes/api/admin/integrations.$id'
import { Route as ApiAdminIntegrationsIdSlackChannelsRouteImport } from './routes/api/admin/integrations.$id.slack-channels'
import { Route as ApiAdminIntegrationsIdRoutesRouteImport } from './routes/api/admin/integrations.$id.routes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardWorkspaceIdRoute = OnboardWorkspaceIdRouteImport.update({
  id: '/onboard/$workspaceId',
  path: '/onboard/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDomainRoute = DashboardDomainRouteImport.update({
  id: '/dashboard/$domain',
  path: '/dashboard/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const BDomainRoute = BDomainRouteImport.update({
  id: '/b/$domain',
  path: '/b/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceStateRoute = ApiWorkspaceStateRouteImport.update({
  id: '/api/workspace-state',
  path: '/api/workspace-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteRoute = ApiVoteRouteImport.update({
  id: '/api/vote',
  path: '/api/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyDomainRoute = ApiVerifyDomainRouteImport.update({
  id: '/api/verify-domain',
  path: '/api/verify-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketRoute = ApiTicketRouteImport.update({
  id: '/api/ticket',
  path: '/api/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotUploadRoute = ApiScreenshotUploadRouteImport.update({
  id: '/api/screenshot-upload',
  path: '/api/screenshot-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentRoute = ApiCommentRouteImport.update({
  id: '/api/comment',
  path: '/api/comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStateRoute = ApiAuthStateRouteImport.update({
  id: '/api/auth-state',
  path: '/api/auth-state',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDomainIndexRoute = DashboardDomainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDomainRoute,
} as any)
const DashboardBillingSuccessRoute = DashboardBillingSuccessRouteImport.update({
  id: '/dashboard/billing/success',
  path: '/dashboard/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDomainSettingsRoute = DashboardDomainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardDomainRoute,
} as any)
const DashboardDomainIntegrationsRoute =
  DashboardDomainIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => DashboardDomainRoute,
  } as any)
const DashboardDomainDeliveriesRoute =
  DashboardDomainDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => DashboardDomainRoute,
  } as any)
const DashboardDomainClaimRoute = DashboardDomainClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => DashboardDomainRoute,
} as any)
const DashboardDomainBillingRoute = DashboardDomainBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardDomainRoute,
} as any)
const ApiSignupStartCheckoutRoute = ApiSignupStartCheckoutRouteImport.update({
  id: '/api/signup/start-checkout',
  path: '/api/signup/start-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupAbandonRoute = ApiSignupAbandonRouteImport.update({
  id: '/api/signup/abandon',
  path: '/api/signup/abandon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotKeyRoute = ApiScreenshotKeyRouteImport.update({
  id: '/api/screenshot/$key',
  path: '/api/screenshot/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTicketsRoute = ApiPublicTicketsRouteImport.update({
  id: '/api/public/tickets',
  path: '/api/public/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardRenameRoute = ApiOnboardRenameRouteImport.update({
  id: '/api/onboard/rename',
  path: '/api/onboard/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeWorkspacesRoute = ApiMeWorkspacesRouteImport.update({
  id: '/api/me/workspaces',
  path: '/api/me/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTicketsRoute = ApiAdminTicketsRouteImport.update({
  id: '/api/admin/tickets',
  path: '/api/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRedriveRoute = ApiAdminRedriveRouteImport.update({
  id: '/api/admin/redrive',
  path: '/api/admin/redrive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIntegrationsRoute = ApiAdminIntegrationsRouteImport.update({
  id: '/api/admin/integrations',
  path: '/api/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliveriesRoute = ApiAdminDeliveriesRouteImport.update({
  id: '/api/admin/deliveries',
  path: '/api/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBillingSummaryRoute = ApiAdminBillingSummaryRouteImport.update({
  id: '/api/admin/billing-summary',
  path: '/api/admin/billing-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDomainTicketsIdRoute =
  DashboardDomainTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => DashboardDomainRoute,
  } as any)
const ApiIntegrationsSlackInstallRoute =
  ApiIntegrationsSlackInstallRouteImport.update({
    id: '/api/integrations/slack/install',
    path: '/api/integrations/slack/install',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTicketsIdRoute = ApiAdminTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminTicketsRoute,
} as any)
const ApiAdminIntegrationsIdRoute = ApiAdminIntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminIntegrationsRoute,
} as any)
const ApiAdminIntegrationsIdSlackChannelsRoute =
  ApiAdminIntegrationsIdSlackChannelsRouteImport.update({
    id: '/slack-channels',
    path: '/slack-channels',
    getParentRoute: () => ApiAdminIntegrationsIdRoute,
  } as any)
const ApiAdminIntegrationsIdRoutesRoute =
  ApiAdminIntegrationsIdRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => ApiAdminIntegrationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth-state': typeof ApiAuthStateRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/screenshot-upload': typeof ApiScreenshotUploadRoute
  '/api/ticket': typeof ApiTicketRoute
  '/api/verify-domain': typeof ApiVerifyDomainRoute
  '/api/vote': typeof ApiVoteRoute
  '/api/workspace-state': typeof ApiWorkspaceStateRoute
  '/b/$domain': typeof BDomainRoute
  '/dashboard/$domain': typeof DashboardDomainRouteWithChildren
  '/onboard/$workspaceId': typeof OnboardWorkspaceIdRoute
  '/api/admin/billing-summary': typeof ApiAdminBillingSummaryRoute
  '/api/admin/deliveries': typeof ApiAdminDeliveriesRoute
  '/api/admin/integrations': typeof ApiAdminIntegrationsRouteWithChildren
  '/api/admin/redrive': typeof ApiAdminRedriveRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/workspaces': typeof ApiMeWorkspacesRoute
  '/api/onboard/rename': typeof ApiOnboardRenameRoute
  '/api/public/tickets': typeof ApiPublicTicketsRoute
  '/api/screenshot/$key': typeof ApiScreenshotKeyRoute
  '/api/signup/abandon': typeof ApiSignupAbandonRoute
  '/api/signup/start-checkout': typeof ApiSignupStartCheckoutRoute
  '/dashboard/$domain/billing': typeof DashboardDomainBillingRoute
  '/dashboard/$domain/claim': typeof DashboardDomainClaimRoute
  '/dashboard/$domain/deliveries': typeof DashboardDomainDeliveriesRoute
  '/dashboard/$domain/integrations': typeof DashboardDomainIntegrationsRoute
  '/dashboard/$domain/settings': typeof DashboardDomainSettingsRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/$domain/': typeof DashboardDomainIndexRoute
  '/api/admin/integrations/$id': typeof ApiAdminIntegrationsIdRouteWithChildren
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/install': typeof ApiIntegrationsSlackInstallRoute
  '/dashboard/$domain/tickets/$id': typeof DashboardDomainTicketsIdRoute
  '/api/admin/integrations/$id/routes': typeof ApiAdminIntegrationsIdRoutesRoute
  '/api/admin/integrations/$id/slack-channels': typeof ApiAdminIntegrationsIdSlackChannelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth-state': typeof ApiAuthStateRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/screenshot-upload': typeof ApiScreenshotUploadRoute
  '/api/ticket': typeof ApiTicketRoute
  '/api/verify-domain': typeof ApiVerifyDomainRoute
  '/api/vote': typeof ApiVoteRoute
  '/api/workspace-state': typeof ApiWorkspaceStateRoute
  '/b/$domain': typeof BDomainRoute
  '/onboard/$workspaceId': typeof OnboardWorkspaceIdRoute
  '/api/admin/billing-summary': typeof ApiAdminBillingSummaryRoute
  '/api/admin/deliveries': typeof ApiAdminDeliveriesRoute
  '/api/admin/integrations': typeof ApiAdminIntegrationsRouteWithChildren
  '/api/admin/redrive': typeof ApiAdminRedriveRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/workspaces': typeof ApiMeWorkspacesRoute
  '/api/onboard/rename': typeof ApiOnboardRenameRoute
  '/api/public/tickets': typeof ApiPublicTicketsRoute
  '/api/screenshot/$key': typeof ApiScreenshotKeyRoute
  '/api/signup/abandon': typeof ApiSignupAbandonRoute
  '/api/signup/start-checkout': typeof ApiSignupStartCheckoutRoute
  '/dashboard/$domain/billing': typeof DashboardDomainBillingRoute
  '/dashboard/$domain/claim': typeof DashboardDomainClaimRoute
  '/dashboard/$domain/deliveries': typeof DashboardDomainDeliveriesRoute
  '/dashboard/$domain/integrations': typeof DashboardDomainIntegrationsRoute
  '/dashboard/$domain/settings': typeof DashboardDomainSettingsRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/$domain': typeof DashboardDomainIndexRoute
  '/api/admin/integrations/$id': typeof ApiAdminIntegrationsIdRouteWithChildren
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/install': typeof ApiIntegrationsSlackInstallRoute
  '/dashboard/$domain/tickets/$id': typeof DashboardDomainTicketsIdRoute
  '/api/admin/integrations/$id/routes': typeof ApiAdminIntegrationsIdRoutesRoute
  '/api/admin/integrations/$id/slack-channels': typeof ApiAdminIntegrationsIdSlackChannelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/auth-state': typeof ApiAuthStateRoute
  '/api/comment': typeof ApiCommentRoute
  '/api/screenshot-upload': typeof ApiScreenshotUploadRoute
  '/api/ticket': typeof ApiTicketRoute
  '/api/verify-domain': typeof ApiVerifyDomainRoute
  '/api/vote': typeof ApiVoteRoute
  '/api/workspace-state': typeof ApiWorkspaceStateRoute
  '/b/$domain': typeof BDomainRoute
  '/dashboard/$domain': typeof DashboardDomainRouteWithChildren
  '/onboard/$workspaceId': typeof OnboardWorkspaceIdRoute
  '/api/admin/billing-summary': typeof ApiAdminBillingSummaryRoute
  '/api/admin/deliveries': typeof ApiAdminDeliveriesRoute
  '/api/admin/integrations': typeof ApiAdminIntegrationsRouteWithChildren
  '/api/admin/redrive': typeof ApiAdminRedriveRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/me/workspaces': typeof ApiMeWorkspacesRoute
  '/api/onboard/rename': typeof ApiOnboardRenameRoute
  '/api/public/tickets': typeof ApiPublicTicketsRoute
  '/api/screenshot/$key': typeof ApiScreenshotKeyRoute
  '/api/signup/abandon': typeof ApiSignupAbandonRoute
  '/api/signup/start-checkout': typeof ApiSignupStartCheckoutRoute
  '/dashboard/$domain/billing': typeof DashboardDomainBillingRoute
  '/dashboard/$domain/claim': typeof DashboardDomainClaimRoute
  '/dashboard/$domain/deliveries': typeof DashboardDomainDeliveriesRoute
  '/dashboard/$domain/integrations': typeof DashboardDomainIntegrationsRoute
  '/dashboard/$domain/settings': typeof DashboardDomainSettingsRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/$domain/': typeof DashboardDomainIndexRoute
  '/api/admin/integrations/$id': typeof ApiAdminIntegrationsIdRouteWithChildren
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/install': typeof ApiIntegrationsSlackInstallRoute
  '/dashboard/$domain/tickets/$id': typeof DashboardDomainTicketsIdRoute
  '/api/admin/integrations/$id/routes': typeof ApiAdminIntegrationsIdRoutesRoute
  '/api/admin/integrations/$id/slack-channels': typeof ApiAdminIntegrationsIdSlackChannelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth-state'
    | '/api/comment'
    | '/api/screenshot-upload'
    | '/api/ticket'
    | '/api/verify-domain'
    | '/api/vote'
    | '/api/workspace-state'
    | '/b/$domain'
    | '/dashboard/$domain'
    | '/onboard/$workspaceId'
    | '/api/admin/billing-summary'
    | '/api/admin/deliveries'
    | '/api/admin/integrations'
    | '/api/admin/redrive'
    | '/api/admin/tickets'
    | '/api/auth/$'
    | '/api/me/workspaces'
    | '/api/onboard/rename'
    | '/api/public/tickets'
    | '/api/screenshot/$key'
    | '/api/signup/abandon'
    | '/api/signup/start-checkout'
    | '/dashboard/$domain/billing'
    | '/dashboard/$domain/claim'
    | '/dashboard/$domain/deliveries'
    | '/dashboard/$domain/integrations'
    | '/dashboard/$domain/settings'
    | '/dashboard/billing/success'
    | '/dashboard/$domain/'
    | '/api/admin/integrations/$id'
    | '/api/admin/tickets/$id'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/install'
    | '/dashboard/$domain/tickets/$id'
    | '/api/admin/integrations/$id/routes'
    | '/api/admin/integrations/$id/slack-channels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth-state'
    | '/api/comment'
    | '/api/screenshot-upload'
    | '/api/ticket'
    | '/api/verify-domain'
    | '/api/vote'
    | '/api/workspace-state'
    | '/b/$domain'
    | '/onboard/$workspaceId'
    | '/api/admin/billing-summary'
    | '/api/admin/deliveries'
    | '/api/admin/integrations'
    | '/api/admin/redrive'
    | '/api/admin/tickets'
    | '/api/auth/$'
    | '/api/me/workspaces'
    | '/api/onboard/rename'
    | '/api/public/tickets'
    | '/api/screenshot/$key'
    | '/api/signup/abandon'
    | '/api/signup/start-checkout'
    | '/dashboard/$domain/billing'
    | '/dashboard/$domain/claim'
    | '/dashboard/$domain/deliveries'
    | '/dashboard/$domain/integrations'
    | '/dashboard/$domain/settings'
    | '/dashboard/billing/success'
    | '/dashboard/$domain'
    | '/api/admin/integrations/$id'
    | '/api/admin/tickets/$id'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/install'
    | '/dashboard/$domain/tickets/$id'
    | '/api/admin/integrations/$id/routes'
    | '/api/admin/integrations/$id/slack-channels'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/api/auth-state'
    | '/api/comment'
    | '/api/screenshot-upload'
    | '/api/ticket'
    | '/api/verify-domain'
    | '/api/vote'
    | '/api/workspace-state'
    | '/b/$domain'
    | '/dashboard/$domain'
    | '/onboard/$workspaceId'
    | '/api/admin/billing-summary'
    | '/api/admin/deliveries'
    | '/api/admin/integrations'
    | '/api/admin/redrive'
    | '/api/admin/tickets'
    | '/api/auth/$'
    | '/api/me/workspaces'
    | '/api/onboard/rename'
    | '/api/public/tickets'
    | '/api/screenshot/$key'
    | '/api/signup/abandon'
    | '/api/signup/start-checkout'
    | '/dashboard/$domain/billing'
    | '/dashboard/$domain/claim'
    | '/dashboard/$domain/deliveries'
    | '/dashboard/$domain/integrations'
    | '/dashboard/$domain/settings'
    | '/dashboard/billing/success'
    | '/dashboard/$domain/'
    | '/api/admin/integrations/$id'
    | '/api/admin/tickets/$id'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/install'
    | '/dashboard/$domain/tickets/$id'
    | '/api/admin/integrations/$id/routes'
    | '/api/admin/integrations/$id/slack-channels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthStateRoute: typeof ApiAuthStateRoute
  ApiCommentRoute: typeof ApiCommentRoute
  ApiScreenshotUploadRoute: typeof ApiScreenshotUploadRoute
  ApiTicketRoute: typeof ApiTicketRoute
  ApiVerifyDomainRoute: typeof ApiVerifyDomainRoute
  ApiVoteRoute: typeof ApiVoteRoute
  ApiWorkspaceStateRoute: typeof ApiWorkspaceStateRoute
  BDomainRoute: typeof BDomainRoute
  DashboardDomainRoute: typeof DashboardDomainRouteWithChildren
  OnboardWorkspaceIdRoute: typeof OnboardWorkspaceIdRoute
  ApiAdminBillingSummaryRoute: typeof ApiAdminBillingSummaryRoute
  ApiAdminDeliveriesRoute: typeof ApiAdminDeliveriesRoute
  ApiAdminIntegrationsRoute: typeof ApiAdminIntegrationsRouteWithChildren
  ApiAdminRedriveRoute: typeof ApiAdminRedriveRoute
  ApiAdminTicketsRoute: typeof ApiAdminTicketsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMeWorkspacesRoute: typeof ApiMeWorkspacesRoute
  ApiOnboardRenameRoute: typeof ApiOnboardRenameRoute
  ApiPublicTicketsRoute: typeof ApiPublicTicketsRoute
  ApiScreenshotKeyRoute: typeof ApiScreenshotKeyRoute
  ApiSignupAbandonRoute: typeof ApiSignupAbandonRoute
  ApiSignupStartCheckoutRoute: typeof ApiSignupStartCheckoutRoute
  DashboardBillingSuccessRoute: typeof DashboardBillingSuccessRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
  ApiIntegrationsSlackInstallRoute: typeof ApiIntegrationsSlackInstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$workspaceId': {
      id: '/onboard/$workspaceId'
      path: '/onboard/$workspaceId'
      fullPath: '/onboard/$workspaceId'
      preLoaderRoute: typeof OnboardWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$domain': {
      id: '/dashboard/$domain'
      path: '/dashboard/$domain'
      fullPath: '/dashboard/$domain'
      preLoaderRoute: typeof DashboardDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$domain': {
      id: '/b/$domain'
      path: '/b/$domain'
      fullPath: '/b/$domain'
      preLoaderRoute: typeof BDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace-state': {
      id: '/api/workspace-state'
      path: '/api/workspace-state'
      fullPath: '/api/workspace-state'
      preLoaderRoute: typeof ApiWorkspaceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote': {
      id: '/api/vote'
      path: '/api/vote'
      fullPath: '/api/vote'
      preLoaderRoute: typeof ApiVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-domain': {
      id: '/api/verify-domain'
      path: '/api/verify-domain'
      fullPath: '/api/verify-domain'
      preLoaderRoute: typeof ApiVerifyDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ticket': {
      id: '/api/ticket'
      path: '/api/ticket'
      fullPath: '/api/ticket'
      preLoaderRoute: typeof ApiTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot-upload': {
      id: '/api/screenshot-upload'
      path: '/api/screenshot-upload'
      fullPath: '/api/screenshot-upload'
      preLoaderRoute: typeof ApiScreenshotUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comment': {
      id: '/api/comment'
      path: '/api/comment'
      fullPath: '/api/comment'
      preLoaderRoute: typeof ApiCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-state': {
      id: '/api/auth-state'
      path: '/api/auth-state'
      fullPath: '/api/auth-state'
      preLoaderRoute: typeof ApiAuthStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$domain/': {
      id: '/dashboard/$domain/'
      path: '/'
      fullPath: '/dashboard/$domain/'
      preLoaderRoute: typeof DashboardDomainIndexRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/dashboard/billing/success': {
      id: '/dashboard/billing/success'
      path: '/dashboard/billing/success'
      fullPath: '/dashboard/billing/success'
      preLoaderRoute: typeof DashboardBillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$domain/settings': {
      id: '/dashboard/$domain/settings'
      path: '/settings'
      fullPath: '/dashboard/$domain/settings'
      preLoaderRoute: typeof DashboardDomainSettingsRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/dashboard/$domain/integrations': {
      id: '/dashboard/$domain/integrations'
      path: '/integrations'
      fullPath: '/dashboard/$domain/integrations'
      preLoaderRoute: typeof DashboardDomainIntegrationsRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/dashboard/$domain/deliveries': {
      id: '/dashboard/$domain/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/$domain/deliveries'
      preLoaderRoute: typeof DashboardDomainDeliveriesRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/dashboard/$domain/claim': {
      id: '/dashboard/$domain/claim'
      path: '/claim'
      fullPath: '/dashboard/$domain/claim'
      preLoaderRoute: typeof DashboardDomainClaimRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/dashboard/$domain/billing': {
      id: '/dashboard/$domain/billing'
      path: '/billing'
      fullPath: '/dashboard/$domain/billing'
      preLoaderRoute: typeof DashboardDomainBillingRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/api/signup/start-checkout': {
      id: '/api/signup/start-checkout'
      path: '/api/signup/start-checkout'
      fullPath: '/api/signup/start-checkout'
      preLoaderRoute: typeof ApiSignupStartCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup/abandon': {
      id: '/api/signup/abandon'
      path: '/api/signup/abandon'
      fullPath: '/api/signup/abandon'
      preLoaderRoute: typeof ApiSignupAbandonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot/$key': {
      id: '/api/screenshot/$key'
      path: '/api/screenshot/$key'
      fullPath: '/api/screenshot/$key'
      preLoaderRoute: typeof ApiScreenshotKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tickets': {
      id: '/api/public/tickets'
      path: '/api/public/tickets'
      fullPath: '/api/public/tickets'
      preLoaderRoute: typeof ApiPublicTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboard/rename': {
      id: '/api/onboard/rename'
      path: '/api/onboard/rename'
      fullPath: '/api/onboard/rename'
      preLoaderRoute: typeof ApiOnboardRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/workspaces': {
      id: '/api/me/workspaces'
      path: '/api/me/workspaces'
      fullPath: '/api/me/workspaces'
      preLoaderRoute: typeof ApiMeWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tickets': {
      id: '/api/admin/tickets'
      path: '/api/admin/tickets'
      fullPath: '/api/admin/tickets'
      preLoaderRoute: typeof ApiAdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/redrive': {
      id: '/api/admin/redrive'
      path: '/api/admin/redrive'
      fullPath: '/api/admin/redrive'
      preLoaderRoute: typeof ApiAdminRedriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/integrations': {
      id: '/api/admin/integrations'
      path: '/api/admin/integrations'
      fullPath: '/api/admin/integrations'
      preLoaderRoute: typeof ApiAdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliveries': {
      id: '/api/admin/deliveries'
      path: '/api/admin/deliveries'
      fullPath: '/api/admin/deliveries'
      preLoaderRoute: typeof ApiAdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/billing-summary': {
      id: '/api/admin/billing-summary'
      path: '/api/admin/billing-summary'
      fullPath: '/api/admin/billing-summary'
      preLoaderRoute: typeof ApiAdminBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$domain/tickets/$id': {
      id: '/dashboard/$domain/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/dashboard/$domain/tickets/$id'
      preLoaderRoute: typeof DashboardDomainTicketsIdRouteImport
      parentRoute: typeof DashboardDomainRoute
    }
    '/api/integrations/slack/install': {
      id: '/api/integrations/slack/install'
      path: '/api/integrations/slack/install'
      fullPath: '/api/integrations/slack/install'
      preLoaderRoute: typeof ApiIntegrationsSlackInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tickets/$id': {
      id: '/api/admin/tickets/$id'
      path: '/$id'
      fullPath: '/api/admin/tickets/$id'
      preLoaderRoute: typeof ApiAdminTicketsIdRouteImport
      parentRoute: typeof ApiAdminTicketsRoute
    }
    '/api/admin/integrations/$id': {
      id: '/api/admin/integrations/$id'
      path: '/$id'
      fullPath: '/api/admin/integrations/$id'
      preLoaderRoute: typeof ApiAdminIntegrationsIdRouteImport
      parentRoute: typeof ApiAdminIntegrationsRoute
    }
    '/api/admin/integrations/$id/slack-channels': {
      id: '/api/admin/integrations/$id/slack-channels'
      path: '/slack-channels'
      fullPath: '/api/admin/integrations/$id/slack-channels'
      preLoaderRoute: typeof ApiAdminIntegrationsIdSlackChannelsRouteImport
      parentRoute: typeof ApiAdminIntegrationsIdRoute
    }
    '/api/admin/integrations/$id/routes': {
      id: '/api/admin/integrations/$id/routes'
      path: '/routes'
      fullPath: '/api/admin/integrations/$id/routes'
      preLoaderRoute: typeof ApiAdminIntegrationsIdRoutesRouteImport
      parentRoute: typeof ApiAdminIntegrationsIdRoute
    }
  }
}

interface DashboardDomainRouteChildren {
  DashboardDomainBillingRoute: typeof DashboardDomainBillingRoute
  DashboardDomainClaimRoute: typeof DashboardDomainClaimRoute
  DashboardDomainDeliveriesRoute: typeof DashboardDomainDeliveriesRoute
  DashboardDomainIntegrationsRoute: typeof DashboardDomainIntegrationsRoute
  DashboardDomainSettingsRoute: typeof DashboardDomainSettingsRoute
  DashboardDomainIndexRoute: typeof DashboardDomainIndexRoute
  DashboardDomainTicketsIdRoute: typeof DashboardDomainTicketsIdRoute
}

const DashboardDomainRouteChildren: DashboardDomainRouteChildren = {
  DashboardDomainBillingRoute: DashboardDomainBillingRoute,
  DashboardDomainClaimRoute: DashboardDomainClaimRoute,
  DashboardDomainDeliveriesRoute: DashboardDomainDeliveriesRoute,
  DashboardDomainIntegrationsRoute: DashboardDomainIntegrationsRoute,
  DashboardDomainSettingsRoute: DashboardDomainSettingsRoute,
  DashboardDomainIndexRoute: DashboardDomainIndexRoute,
  DashboardDomainTicketsIdRoute: DashboardDomainTicketsIdRoute,
}

const DashboardDomainRouteWithChildren = DashboardDomainRoute._addFileChildren(
  DashboardDomainRouteChildren,
)

interface ApiAdminIntegrationsIdRouteChildren {
  ApiAdminIntegrationsIdRoutesRoute: typeof ApiAdminIntegrationsIdRoutesRoute
  ApiAdminIntegrationsIdSlackChannelsRoute: typeof ApiAdminIntegrationsIdSlackChannelsRoute
}

const ApiAdminIntegrationsIdRouteChildren: ApiAdminIntegrationsIdRouteChildren =
  {
    ApiAdminIntegrationsIdRoutesRoute: ApiAdminIntegrationsIdRoutesRoute,
    ApiAdminIntegrationsIdSlackChannelsRoute:
      ApiAdminIntegrationsIdSlackChannelsRoute,
  }

const ApiAdminIntegrationsIdRouteWithChildren =
  ApiAdminIntegrationsIdRoute._addFileChildren(
    ApiAdminIntegrationsIdRouteChildren,
  )

interface ApiAdminIntegrationsRouteChildren {
  ApiAdminIntegrationsIdRoute: typeof ApiAdminIntegrationsIdRouteWithChildren
}

const ApiAdminIntegrationsRouteChildren: ApiAdminIntegrationsRouteChildren = {
  ApiAdminIntegrationsIdRoute: ApiAdminIntegrationsIdRouteWithChildren,
}

const ApiAdminIntegrationsRouteWithChildren =
  ApiAdminIntegrationsRoute._addFileChildren(ApiAdminIntegrationsRouteChildren)

interface ApiAdminTicketsRouteChildren {
  ApiAdminTicketsIdRoute: typeof ApiAdminTicketsIdRoute
}

const ApiAdminTicketsRouteChildren: ApiAdminTicketsRouteChildren = {
  ApiAdminTicketsIdRoute: ApiAdminTicketsIdRoute,
}

const ApiAdminTicketsRouteWithChildren = ApiAdminTicketsRoute._addFileChildren(
  ApiAdminTicketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthStateRoute: ApiAuthStateRoute,
  ApiCommentRoute: ApiCommentRoute,
  ApiScreenshotUploadRoute: ApiScreenshotUploadRoute,
  ApiTicketRoute: ApiTicketRoute,
  ApiVerifyDomainRoute: ApiVerifyDomainRoute,
  ApiVoteRoute: ApiVoteRoute,
  ApiWorkspaceStateRoute: ApiWorkspaceStateRoute,
  BDomainRoute: BDomainRoute,
  DashboardDomainRoute: DashboardDomainRouteWithChildren,
  OnboardWorkspaceIdRoute: OnboardWorkspaceIdRoute,
  ApiAdminBillingSummaryRoute: ApiAdminBillingSummaryRoute,
  ApiAdminDeliveriesRoute: ApiAdminDeliveriesRoute,
  ApiAdminIntegrationsRoute: ApiAdminIntegrationsRouteWithChildren,
  ApiAdminRedriveRoute: ApiAdminRedriveRoute,
  ApiAdminTicketsRoute: ApiAdminTicketsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMeWorkspacesRoute: ApiMeWorkspacesRoute,
  ApiOnboardRenameRoute: ApiOnboardRenameRoute,
  ApiPublicTicketsRoute: ApiPublicTicketsRoute,
  ApiScreenshotKeyRoute: ApiScreenshotKeyRoute,
  ApiSignupAbandonRoute: ApiSignupAbandonRoute,
  ApiSignupStartCheckoutRoute: ApiSignupStartCheckoutRoute,
  DashboardBillingSuccessRoute: DashboardBillingSuccessRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
  ApiIntegrationsSlackInstallRoute: ApiIntegrationsSlackInstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
